disabled_rules:
   - line_length
   - cyclomatic_complexity
   - function_body_length
   - identifier_name
   - force_cast
   - file_length
   - shorthand_operator
   - type_body_length
   - large_tuple
   - todo


excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Source/ExcludedFolder

